version: "3.8"
#name: 'api-money-transfer'
services:
  ###### ratings-db config ###########
  ratings-db:
    image: postgres:16-alpine
    container_name: ratings-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m