package com.loulysoft.moneytransfer.accounting.enums;

public enum ServiceContextItem {
    PRINCIPAL_SERVICE_CONTEXT,
    PROVISION_SERVICE_CONTEXT,
    DESTINATION_COUNTRY_ISOCODE,
    TRANSFER_PROCESSOR_PARTNER,
    ACCOUNTING_SCHEMA_VARIANTE,
    DESTINATION_AMOUNT,
    TRANSFER_DETAIL,
    PRINCIPAL_EXTERNE_SERVICE_CONTEXT,
    PROVISION_EXTERNE_SERVICE_CONTEXT,
    FRAIS_TRANSFERT_ADDITIONNEL,
    AUTRE_PARAMETRE,
    MESSAGE,
    NATURE_SERVICE;
}
