package com.loulysoft.moneytransfer.accounting.enums;

public enum TransactionContextItem {
    LAUNCH_ACTOR("LAUNCH_ACTOR"),
    TRANSACTION_REF_ID("TRANSACTION_REF_ID"),
    LAUNCH_FINANCIAL_ENTITY("LAUNCH_FINANCIAL_ENTITY"),
    ROUTE("ROUTE"),
    PRINCIPAL("PRINCIPAL"),
    PRINCIPAL_FEE("PRINCIPAL_FEE"),
    DESTINATION_COUNTRY("DESTINATION_COUNTRY"),
    SENDER_COUNTRY("SENDER_COUNTRY"),
    DESTINATION_COMPANY_ID("DESTINATION_COMPANY_ID"),
    DEVISE("DEVISE"),
    TRANSACTION_INFOS("TRANSACTION_INFOS"),
    MOTIF("MOTIF"),
    COMPANY_ID("COMPANY_ID"),
    QUESTION("QUESTION"),
    REPONSE("REPONSE"),
    MESSAGE("MESSAGE"),
    PRINCIPAL_CONVERTI("PRINCIPAL_CONVERTI"),
    COMMISSION("COMMISSION"),
    TAUX_CHANGE("TAUX_CHANGE"),
    NUMERO_TRANSACTION("NUMERO_TRANSACTION"),
    RABAIS("RABAIS"),
    SERVICE_CONTEXT("SERVICE_CONTEXT"),
    UNITE_ORGANISATIONNELLE_TIERCE_REFERENCE("UNITE_ORGANISATIONNELLE_TIERCE_REFERENCE"),
    TRANSFER_SENDER("TRANSFER_SENDER"),
    TRANSFER_RECEIVER("TRANSFER_RECEIVER"),
    CODE("CODE"),
    TRANSACTION_PROPERTY_VALUES("TRANSACTION_PROPERTY_VALUES"),
    PARTENAIRE_TRANSACTION_ID("PARTENAIRE_TRANSACTION_ID"),
    OPTION_PAIEMENT_TRANSFERT("OPTION_PAIEMENT_TRANSFERT"),
    ORIGIN_TRANS_ID("ORIGIN_TRANS_ID"),
    SERVICE_NAME("SERVICE_NAME"),
    NATURE_SERVICE("NATURE_SERVICE"),
    JOURNAL_INFOS("JOURNAL_INFOS");

    final String name;

    TransactionContextItem(String name) {
        this.name = name;
    }
}
